# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BasicStat <- function(dist, cluster_) {
    .Call('ClusterTools_BasicStat', PACKAGE = 'ClusterTools', dist, cluster_)
}

ClusterCompare <- function(cluster_1, cluster_2) {
    .Call('ClusterTools_ClusterCompare', PACKAGE = 'ClusterTools', cluster_1, cluster_2)
}

afk_mc2 <- function(k, m, M, threads) {
    .Call('ClusterTools_afk_mc2', PACKAGE = 'ClusterTools', k, m, M, threads)
}

permutate <- function(x) {
    .Call('ClusterTools_permutate', PACKAGE = 'ClusterTools', x)
}

ParallelSilhouette <- function(dist, num_cases, cluster, num_clusters, threads = 1L) {
    .Call('ClusterTools_ParallelSilhouette', PACKAGE = 'ClusterTools', dist, num_cases, cluster, num_clusters, threads)
}

test1 <- function(x) {
    .Call('ClusterTools_test1', PACKAGE = 'ClusterTools', x)
}

test2 <- function(x) {
    .Call('ClusterTools_test2', PACKAGE = 'ClusterTools', x)
}

